version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diet_backend
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diet_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend